name: Unit Test, Build Docker Image, Deploy to Swarm
on:
  push:
    branches:
      - 'development'


jobs:
  build-push-docker:
    name: 'Build image and push to registry'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build docker
        run: docker build -t stevenfrst/ppob-frontend .
      - name: login dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: push the previously built image to registry
        run: docker push stevenfrst/ppob-frontend
  deploy-to-swarm:
    runs-on: ubuntu-latest
    needs: build-push-docker
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/ppob-frontend/
            git checkout development
            git pull origin development
            docker stack deploy -c docker-compose.yml gesek
